/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2026-03-24 19:52:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import bank.model.Transaction;

public final class adminPanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("bank.model.Transaction");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Admin Mode - JavaBank</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css\"/>\n");
      out.write("    <style>\n");
      out.write("        body { margin: 0; padding: 0; background: linear-gradient(135deg, #f0f8ff 0%, #b3d4ff 100%); min-height: 100vh; font-family: 'Inter', sans-serif; }\n");
      out.write("        .container { max-width: 1000px; margin: 40px auto; padding: 0 20px; }\n");
      out.write("        \n");
      out.write("        table.dataTable thead th { \n");
      out.write("            background-color: #1a4a76 !important; \n");
      out.write("            color: #ffffff !important; \n");
      out.write("            border-bottom: none !important;\n");
      out.write("            padding: 12px 15px;\n");
      out.write("            font-size: 15px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        table.dataTable tbody tr:hover { background-color: #e9f2fb !important; }\n");
      out.write("        \n");
      out.write("        .filter-section {\n");
      out.write("            background: white; padding: 15px 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 5px rgba(0,0,0,0.05);\n");
      out.write("            display: flex; align-items: center; gap: 15px;\n");
      out.write("        }\n");
      out.write("        .filter-section select {\n");
      out.write("            padding: 8px 12px; border: 1px solid #ced4da; border-radius: 5px; font-size: 14px; cursor: pointer; outline: none; background: #f8f9fa;\n");
      out.write("        }\n");
      out.write("        .filter-section select:focus { border-color: #1a4a76; }\n");
      out.write("        \n");
      out.write("        .header-section {\n");
      out.write("            display: flex; justify-content: space-between; align-items: center; margin-bottom: 25px;\n");
      out.write("        }\n");
      out.write("        .header-section h1 {\n");
      out.write("            color: #1a4a76; margin: 0; font-size: 28px;\n");
      out.write("        }\n");
      out.write("        .header-links a {\n");
      out.write("            text-decoration: none; font-weight: bold; font-size: 16px; margin-left: 20px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"header-section\">\n");
      out.write("        <h1>Admin Mode</h1>\n");
      out.write("        <div class=\"header-links\">\n");
      out.write("            <a href=\"dashboard\" style=\"color: #1a4a76;\">Dashboard</a>\n");
      out.write("            <a href=\"logout\" style=\"color: #dc3545;\">Logout</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"filter-section\">\n");
      out.write("        <label for=\"typeSelect\" style=\"font-weight: bold; color: #333; font-size: 15px;\">Filter by Transaction:</label>\n");
      out.write("        <select id=\"typeSelect\">\n");
      out.write("            <option value=\"\">All Transactions</option>\n");
      out.write("            <option value=\"DEPOSIT\">Deposits Only</option>\n");
      out.write("            <option value=\"WITHDRAW\">Withdrawals Only</option>\n");
      out.write("            <option value=\"TRANSFER_OUT\">Transfers Sent</option>\n");
      out.write("            <option value=\"TRANSFER_IN\">Transfers Received</option>\n");
      out.write("        </select>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div style=\"background: white; padding: 25px; border-radius: 10px; box-shadow: 0 8px 20px rgba(0,0,0,0.08);\">\n");
      out.write("        <table id=\"adminTable\" class=\"display\" style=\"width:100%\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID</th>\n");
      out.write("                    <th>User</th>\n");
      out.write("                    <th>Type</th>\n");
      out.write("                    <th>Description</th>\n");
      out.write("                    <th>Amount</th>\n");
      out.write("                    <th>Date</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                ");

                    List<Transaction> txs = (List<Transaction>) request.getAttribute("transactions");
                    if (txs != null && !txs.isEmpty()) {
                        for (Transaction t : txs) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( t.getId() );
      out.write("</td>\n");
      out.write("                    <td style=\"font-weight: 600; color: #1a4a76;\">");
      out.print( t.getUserName() != null ? t.getUserName() : "Unknown" );
      out.write("</td>\n");
      out.write("                    <td>\n");
      out.write("                        <span style=\"font-weight: bold; background: ");
      out.print( t.getType().contains("IN") || t.getType().equals("DEPOSIT") ? "#d4edda" : "#f8d7da" );
      out.write("; \n");
      out.write("                                     color: ");
      out.print( t.getType().contains("IN") || t.getType().equals("DEPOSIT") ? "#155724" : "#721c24" );
      out.write("; \n");
      out.write("                                     padding: 4px 8px; border-radius: 4px; font-size: 12px;\">\n");
      out.write("                            ");
      out.print( t.getType() );
      out.write("\n");
      out.write("                        </span>\n");
      out.write("                    </td>\n");
      out.write("                    <td style=\"color: #555;\">");
      out.print( t.getDescription() != null ? t.getDescription() : "-" );
      out.write("</td>\n");
      out.write("                    <td style=\"font-weight: 600;\">₹");
      out.print( String.format("%.2f", t.getAmount()) );
      out.write("</td>\n");
      out.write("                    <td style=\"color: #666; font-size: 14px;\">");
      out.print( t.getCreatedAt() );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                ");

                        }
                    }
                
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        var table = $('#adminTable').DataTable({\n");
      out.write("            \"order\": [[ 5, \"desc\" ]], // Sort by date descending\n");
      out.write("            \"pageLength\": 25,\n");
      out.write("            \"language\": {\n");
      out.write("                \"search\": \"Global Search:\"\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Add event listener to the custom select dropdown to filter the Type column (index 2)\n");
      out.write("        $('#typeSelect').on('change', function () {\n");
      out.write("            var val = $.fn.dataTable.util.escapeRegex($(this).val());\n");
      out.write("            // Use word boundary instead of strict start/end to ignore HTML whitespace padding\n");
      out.write("            table.column(2).search(val ? '\\\\b' + val + '\\\\b' : '', true, false).draw();\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
